export const UserDetailsDiToken = {
  USER_DETAILS_REPOSITORY: Symbol('USER_DETAILS_REPOSITORY'),
  CREATE_USER_DETAILS_USE_CASE: Symbol('CREATE_USER_DETAILS_USE_CASE'),
  GET_USER_DETAILS_BY_ID_USE_CASE: Symbol('GET_USER_DETAILS_BY_ID_USE_CASE'),
  USER_DETAILS_QUERY_SERVICE: Symbol('USER_DETAILS_QUERY_SERVICE'),
} as const;
