export const CompaniesDiToken = {
  RUN_COMPANY_SEEDS_USE_CASE: Symbol('RUN_COMPANY_SEEDS_USE_CASE'),
  RUN_COMPANY_PERMISSION_SEEDS_USE_CASE: Symbol('RUN_COMPANY_PERMISSION_SEEDS_USE_CASE'),
  RUN_COMPANY_ROLE_SEEDS_USE_CASE: Symbol('RUN_COMPANY_ROLE_SEEDS_USE_CASE'),
  RUN_COMPANY_ROLE_PERMISSION_SEEDS_USE_CASE: Symbol('RUN_COMPANY_ROLE_PERMISSION_SEEDS_USE_CASE'),

  CREATE_COMPANY_USE_CASE: Symbol('CREATE_COMPANY_USE_CASE'),
  UPDATE_COMPANY_USE_CASE: Symbol('UPDATE_COMPANY_USE_CASE'),

  CREATE_USER_COMPANY_USE_CASE: Symbol('CREATE_USER_COMPANY_USE_CASE'),

  COMPANY_PERMISSION_QUERY_SERVICE: Symbol('COMPANY_PERMISSION_QUERY_SERVICE'),
  COMPANIES_QUERY_SERVICE: Symbol('COMPANIES_QUERY_SERVICE'),
  COMPANY_PERMISSION_REPOSITORY: Symbol('COMPANY_PERMISSION_REPOSITORY'),

  COMPANY_REPOSITORY: Symbol('COMPANY_REPOSITORY'),

  COMPANY_ROLE_REPOSITORY: Symbol('COMPANY_ROLE_REPOSITORY'),
  COMPANY_ROLE_PERMISSION_REPOSITORY: Symbol('COMPANY_ROLE_PERMISSION_REPOSITORY'),

  USER_COMPANY_REPOSITORY: Symbol('USER_COMPANY_REPOSITORY'),
  SEND_INVITATION_USE_CASE: Symbol('SEND_INVITATION_USE_CASE'),
  ACCEPT_INVITATION_USE_CASE: Symbol('ACCEPT_INVITATION_USE_CASE'),

  COMPANY_INVITATION_REPOSITORY: Symbol('COMPANY_INVITATION_REPOSITORY'),
} as const;
