export const CompaniesDiToken = {
  CREATE_COMPANY_USE_CASE: Symbol('CREATE_COMPANY_USE_CASE'),
  UPDATE_COMPANY_USE_CASE: Symbol('UPDATE_COMPANY_USE_CASE'),
  GET_COMPANY_BY_ID_USE_CASE: Symbol('GET_COMPANY_BY_ID_USE_CASE'),
  GET_COMPANY_BY_SLUG_USE_CASE: Symbol('GET_COMPANY_BY_SLUG_USE_CASE'),

  CREATE_USER_COMPANY_USE_CASE: Symbol('CREATE_USER_COMPANY_USE_CASE'),

  COMPANY_PERMISSION_QUERY_SERVICE: Symbol('COMPANY_PERMISSION_QUERY_SERVICE'),
  COMPANIES_QUERY_SERVICE: Symbol('COMPANIES_QUERY_SERVICE'),
  COMPANY_WITH_CATEGORIES_SERVICE: Symbol('COMPANY_WITH_CATEGORIES_SERVICE'),
  COMPANY_PERMISSION_REPOSITORY: Symbol('COMPANY_PERMISSION_REPOSITORY'),

  COMPANY_REPOSITORY: Symbol('COMPANY_REPOSITORY'),
  COMPANY_CATEGORY_REPOSITORY: Symbol('COMPANY_CATEGORY_REPOSITORY'),

  COMPANY_ROLE_REPOSITORY: Symbol('COMPANY_ROLE_REPOSITORY'),
  COMPANY_ROLE_PERMISSION_REPOSITORY: Symbol('COMPANY_ROLE_PERMISSION_REPOSITORY'),

  USER_COMPANY_REPOSITORY: Symbol('USER_COMPANY_REPOSITORY'),
  SEND_INVITATION_USE_CASE: Symbol('SEND_INVITATION_USE_CASE'),
  ACCEPT_INVITATION_USE_CASE: Symbol('ACCEPT_INVITATION_USE_CASE'),

  COMPANY_INVITATION_REPOSITORY: Symbol('COMPANY_INVITATION_REPOSITORY'),
  GET_ALL_COMPANIES_WITH_USERS_USE_CASE: Symbol('GET_ALL_COMPANIES_WITH_USERS_USE_CASE'),
  GET_COMPANIES_BY_RECRUITER_USE_CASE: Symbol('GET_COMPANIES_BY_RECRUITER_USE_CASE'),
} as const;
