export const ProfilesDiToken = {
  USER_DETAILS_REPOSITORY: Symbol('USER_DETAILS_REPOSITORY'),
  GET_USER_DETAILS_BY_USER_ID_USE_CASE: Symbol('GET_USER_DETAILS_BY_USER_ID_USE_CASE'),
  USER_DETAILS_QUERY_SERVICE: Symbol('USER_DETAILS_QUERY_SERVICE'),

  CREATE_USER_PROFILE_USE_CASE: Symbol('CREATE_USER_PROFILE_USE_CASE'),
  GET_USER_PROFILE_WITH_AUTH_USE_CASE: Symbol('GET_USER_PROFILE_WITH_AUTH_USE_CASE'),

  CANDIDATE_PROFILE_REPOSITORY: Symbol('CANDIDATE_PROFILE_REPOSITORY'),
  UPDATE_CANDIDATE_PROFILE_USE_CASE: Symbol('UPDATE_CANDIDATE_PROFILE_USE_CASE'),

  RECRUITER_PROFILE_REPOSITORY: Symbol('RECRUITER_PROFILE_REPOSITORY'),
  GET_RECRUITER_PROFILE_BY_ID_USE_CASE: Symbol('GET_RECRUITER_PROFILE_BY_ID_USE_CASE'),
  GET_RECRUITER_PROFILE_BY_EMAIL_USE_CASE: Symbol('GET_RECRUITER_PROFILE_BY_EMAIL_USE_CASE'),
  UPDATE_RECRUITER_PROFILE_USE_CASE: Symbol('UPDATE_RECRUITER_PROFILE_USE_CASE'),
  // TODO: Rename to RecruiterProfileQueryService
  PROFILES_QUERY_SERVICE: Symbol('PROFILES_QUERY_SERVICE'),
} as const;
