export const RecruiterProfileDiToken = {
  RECRUITER_PROFILE_REPOSITORY: Symbol('RECRUITER_PROFILE_REPOSITORY'),
  CREATE_RECRUITER_PROFILE_USE_CASE: Symbol('CREATE_RECRUITER_PROFILE_USE_CASE'),
  GET_RECRUITER_PROFILE_BY_ID_USE_CASE: Symbol('GET_RECRUITER_PROFILE_BY_ID_USE_CASE'),
  GET_RECRUITER_PROFILE_BY_EMAIL_USE_CASE: Symbol('GET_RECRUITER_PROFILE_BY_EMAIL_USE_CASE'),
  UPDATE_RECRUITER_PROFILE_USE_CASE: Symbol('UPDATE_RECRUITER_PROFILE_USE_CASE'),
  RECRUITER_PROFILE_QUERY_SERVICE: Symbol('RECRUITER_PROFILE_QUERY_SERVICE'),
} as const;
