export const CandidateProfileDiToken = {
  CANDIDATE_PROFILE_REPOSITORY: Symbol('CANDIDATE_PROFILE_REPOSITORY'),
  CREATE_CANDIDATE_PROFILE_USE_CASE: Symbol('CREATE_CANDIDATE_PROFILE_USE_CASE'),
  UPDATE_CANDIDATE_PROFILE_USE_CASE: Symbol('UPDATE_CANDIDATE_PROFILE_USE_CASE'),
  CANDIDATE_PROFILE_QUERY_SERVICE: Symbol('CANDIDATE_PROFILE_QUERY_SERVICE'),
} as const;
