export const FileStorageDiToken = {
  UPLOAD_FILE_USE_CASE: Symbol('UPLOAD_FILE_USE_CASE'),
  DELETE_FILE_USE_CASE: Symbol('DELETE_FILE_USE_CASE'),
  GET_FILE_URL_USE_CASE: Symbol('GET_FILE_URL_USE_CASE'),
  LIST_FILES_USE_CASE: Symbol('LIST_FILES_USE_CASE'),

  FILE_STORAGE_SERVICE: Symbol('FILE_STORAGE_SERVICE'),
  FILE_REPOSITORY: Symbol('FILE_REPOSITORY'),
} as const;
